name: Build App Release
on: [push]
jobs:
  release-build:
    runs-on: ubuntu-latest
    name: Build Release App

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      name: Setup JDK 11
      with:
        java-version: 11

    - run: cd leveldb/src/main/cpp && git clone https://github.com/mojang/leveldb-mcpe.git && cd ../../../../
      name: Setup Submodule

    - run: |
        echo "${{ secrets.KEYSTORE }}" > blocktopograph.jks.asc
        gpg -d --passphrase ${{ secrets.KEYSTORE_PASSPHRASE }} --batch blocktopograph.jks.asc > app/blocktopograph.jks
      name: Setup Signing Key

    - run: ./gradlew -PsigningStorePassword="${{ secrets.SIGNING_STORE_PASSWORD }}" -PsigningKeyAlias="${{ secrets.SIGNING_KEY_ALIAS }}" -PsigningKeyPassword="${{ secrets.SIGNING_KEY_PASSWORD }}" assembleRelease
      name: Building App With Signing Key

    - run: ls -a
      name: Show All Files

    - uses: actions/upload-artifact@v2
      name: Upload APK
      with:
        name: blocktopograph
        path: app/build/outputs/apk/release/blocktopograph-release.apk
