name: Build App Release
on: [push,merge]
jobs:
  release-build:
    runs-on: ubuntu-20.04
    name: Build Release App

    steps:
    - uses: actions/checkout@v2

    - name: Setup JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        cache: 'gradle'

    - name: Building App With Gradle
      runs: ./gradlew assembleRelease --no-daemon

    - name: Pre-Upload APK
      runs: mkdir --parents blocktopograph/app/build/outputs/apk/realease

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: blocktopograph
        path: blocktopograph/app/build/outputs/apk/release/blocktopogrph-release.apk
      
