name: Build App Release
on: [push]
jobs:
  release-build:
    runs-on: ubuntu-20.04
    name: Build Release App

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      name: Setup JDK 11
      with:
        java-version: 11

    - run: cd leveldb/src/main/cpp && git clone https://github.com/mojang/leveldb-mcpe.git && cd ../../../../
      name: Setup Submodule

    - run: ./gradlew assembleRelease --no-daemon
      name: Building App With Gradle

    - run: mkdir --parents blocktopograph/app/build/outputs/apk/realease
      name: Pre-Upload APK

    - uses: actions/upload-artifact@v2
      name: Upload APK
      with:
        name: blocktopograph
        path: blocktopograph/app/build/outputs/apk/release/*.apk
      
